title: ""
labels: ["Product Spec"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the feature or product you're proposing? Provide a 1–2 sentence overview.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the feature or product you're proposing? Provide a 1–2 sentence overview.
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What are the measurable objectives of this feature?
  - type: textarea
    id: nongoals
    attributes:
      label: Non-Goals
      description: What is explicitly out of scope for this release?
  - type: textarea
    id: users
    attributes:
      label: Users
      description: Who are the primary users or personas? How do they benefit?
  - type: textarea
    id: rest
    attributes:
      label: The rest
      value: |
        ## Summary

        What is the feature or product you're proposing? Provide a 1–2 sentence overview.

        ## Problem

        What user need or business goal does this address?

        ## Goals

        What are the measurable objectives of this feature?

        ## Non-Goals

        What is explicitly out of scope for this release?

        ## Users

        Who are the primary users or personas? How do they benefit?

        ## Use Cases

        Describe key scenarios or user stories that this feature should support.

        ## Requirements

        List the high-level requirements:
        - Requirement 1
        - Requirement 2

        ## UX Notes (Optional)

        Include wireframes, mockups, or design ideas if available.

        ## Success Metrics

        How will you measure whether this feature is successful?

        ## Dependencies

        Are there any technical, product, or design dependencies?

        ## Timeline

        What is the rough timeline for implementation and rollout?

        ## Open Questions

        - Question 1
        - Question 2

        ## Future Work

        Mention follow-ups or extensions that are out of scope for now.
