labels: ["Technical Spec"]
body:
  - type: Markdown
    value: Technical spec
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Briefly describe what this spec is about. What’s being proposed?
