labels: ["Product Spec"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the feature or product you're proposing? Provide a 1–2 sentence overview.

