labels: ["Technical Spec"]
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Briefly describe what this spec is about. What’s being proposed?
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are we doing this? What problem does it solve?
  - type: textarea
    id: goals
    attributes:
      label: Goals
      value: |
        - [ ] Goal 1
        - [ ] Goal 2
  - type: textarea
    id: non_goals
    attributes:
      label: Non-Goals
      description: Clarify what is in scope and explicitly out of scope.
  - type: textarea
    id: design_overview
    attributes:
      label: Design Overview
      description: Describe the architecture or high-level technical approach.
      value: |
        Explain the proposed changes in detail:
        - APIs
        - Data models
        - Code structure
        - Dependencies
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List other approaches you evaluated and why they were rejected.
  - type: textarea
    id: risks_and_mitigations
    attributes:
      label: Risks and Mitigations
      description: Identify potential risks and how they can be addressed.
  - type: textarea
    id: open_questions
    attributes:
      label: Open Questions
      placeholder: |
        - Question 1
        - Question 2
  - type: textarea
    id: future_work
    attributes:
      label: Future Work
      description: Mention follow-ups or extensions that are out of scope for now.
